services:
  database:
    image: mariadb:11.5
    container_name: ${APP_NAME}-mariadb
    env_file: ".env.dev.local"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/db-data:/var/lib/mysql:rw
    networks:
      - app

networks:
  app:
    name: ${APP_NAME}_default
    driver: bridge  