services:
  database:
    image: mariadb:11.5
    container_name: mariadb-app
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app_db}
      MARIADB_USER: ${MARIADB_USER:-app_user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "3306:3306"
    volumes:
      # You may use a named volume instead to let docker manage the data for you
      # - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db-data:/var/lib/mysql:rw
    networks:
      - localhost-app

networks:
  localhost-app:
    name: localhost-app
    driver: bridge  

# volumes:
#   database_data: