services:
  database:
    image: mariadb:11.5
    container_name: ${APP_NAME}-mariadb
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${APP_NAME}_db
      - MARIADB_USER=${APP_NAME}_user
      - MARIADB_PASSWORD=${APP_NAME}_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - ./docker/db-data:/var/lib/mysql:rw
    networks:
      - app

networks:
  app:
    name: ${APP_NAME}_default
    driver: bridge  