services:
  database:
    image: mariadb:11.8
    container_name: ${APP_NAME}-mariadb
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    environment:
      - MARIADB_ROOT_PASSWORD=${APP_NAME}_password
      - MARIADB_DATABASE=${APP_NAME}_db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - ./var/mariadb:/var/lib/mysql:rw
    networks:
      - app

networks:
  app:
    name: ${APP_NAME}_default
    driver: bridge  