name: Build and Deploy
run-name: ${{ github.actor }} has build and deploy to prod ðŸš€

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency: one-deploy-at-a-time

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout files in the runner
      uses: actions/checkout@v4

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Cache composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install PHP prod dependencies
      run: composer install --no-scripts --no-interaction --no-progress --prefer-dist --no-dev --optimize-autoloader

    - name: Warm up Symfony cache
      run: php bin/console cache:warmup --env=prod

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    # USELESS as setup-node already cache the packages ?
    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node dependencies
      run: npm install

    - name: Build front end using Webpack Encore 
      run: npm run build

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: build
        include-hidden-files: true
        path: |
          bin/
          config/
          migrations/
          public/
          src/
          templates/
          translations/
          var/
          vendor/
          composer.json
          .env

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment: prod
    steps:
    - name: Setup WARP to enable IPv6
      uses: fscarmen/warp-on-actions@v1.2
      with:
        stack: dual

    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build

    - name: Deploy to prod environment on BAAL
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.BAAL_KEYS }}
        ARGS: "--recursive --links --owner --group --perms --compress --checksum --verbose"
        SOURCE: "build/"
        REMOTE_HOST: ${{ vars.BAAL_ADDR }}
        REMOTE_USER: ${{ secrets.BAAL_USER }}
        REMOTE_PORT: ${{ secrets.BAAL_PORT }}
        TARGET: ${{ vars.BAAL_PATH }}
        SCRIPT_BEFORE: |
          mkdir -p ${{ vars.BAAL_PATH }}
        SCRIPT_AFTER: |
          chmod 775 ${{ vars.BAAL_PATH }}/var
          sudo docker exec -it php-fpm migrate-app ${{ vars.BAAL_PATH }}
   