name: Test, Build, Deploy
run-name: ${{ github.actor }} triggered "Test, Build, Deploy" of version ${{ inputs.version }} to ${{ inputs.environment }} ðŸš€

on:
  workflow_call:
    inputs:
      environment:
        description: 'The deployment environment (stage or prod)'
        required: true
        type: string
      version:
        description: 'The version deployed (x.x.x)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    outputs:
      coverage: ${{ steps.phpunit.outputs.coverage }}
    steps:
    - name: Checkout code in the runner
      uses: actions/checkout@v4

    - name: Setup mysql 8.0
      run: |
        sudo systemctl start mysql.service
        echo 'DATABASE_URL="mysql://root:root@127.0.0.1:3306/symfo-base_db?serverVersion=8.0.44"' > .env.test.local

    - name: Setup php 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: pcov

    - name: Cache composer TEST packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-test-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-test-

    - name: Install php TEST dependencies
      run: composer install --no-scripts --no-interaction --no-progress --prefer-dist
       
    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node dependencies and build assets
      run: |
        npm install
        npm run build

    - name: Run all test suites and check coverage
      id: phpunit
      run: |
        php vendor/bin/phpunit 
        php vendor/bin/coverage-check var/coverage/clover.xml ${{ vars.MIN_COVERAGE }}
        coverage=$(php vendor/bin/coverage-check var/coverage/clover.xml 1 --only-percentage | grep -Eo '[0-9.]+%' | sed 's/%//')
        echo "coverage=$coverage" >> $GITHUB_OUTPUT
        
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code in the runner
      uses: actions/checkout@v4

    - name: Setup php 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Cache composer BUILD packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-build-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-build-

    - name: Install php BUILD dependencies
      run: composer install --no-scripts --no-interaction --no-progress --prefer-dist --no-dev --optimize-autoloader

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node dependencies and build assets
      run: | 
        npm install
        npm run build

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ inputs.version }}
        include-hidden-files: true
        path: |
          bin/
          config/
          migrations/
          public/
          src/
          templates/
          translations/
          vendor/
          composer.json
          .env
          .env.${{ inputs.environment }}

  deploy:
    needs: [test,build]
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
    - name: Setup WARP to enable IPv6
      uses: fscarmen/warp-on-actions@v1.2
      with:
        stack: dual

    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.version }}
        path: build

    - name: Deploy on server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERV_KEYS }}
        ARGS: "--recursive --delete --links --owner --group --perms --compress --checksum --verbose"
        EXCLUDE: "/var/, /.env.local, /.env.${{ inputs.environment }}.local"
        SOURCE: "build/"
        REMOTE_HOST: ${{ vars.SERV_ADDR }}
        REMOTE_USER: ${{ secrets.SERV_USER }}
        REMOTE_PORT: ${{ secrets.SERV_PORT }}
        TARGET: ${{ vars.SERV_PATH }}
        SCRIPT_BEFORE: |
          mkdir -p ${{ vars.SERV_PATH }}
        SCRIPT_AFTER: |
          mkdir -p ${{ vars.SERV_PATH }}/var && chmod 775 ${{ vars.SERV_PATH }}/var
          touch ${{ vars.SERV_PATH }}/.env.local.php && chmod 664 ${{ vars.SERV_PATH }}/.env.local.php
          sudo /usr/bin/docker exec -u php-fpm php-fpm upgrade-app ${{ vars.SERV_PATH }}
          sudo /usr/bin/docker restart php-fpm
   
    - name: Update coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_KEY }}
        gistID: 07bb4b086f8e7dea73754e73bc5c1bb2
        filename: symfo-base-coverage.json
        label: coverage
        message: ${{ needs.test.outputs.coverage }}%
        valColorRange: ${{ needs.test.outputs.coverage }}
        minColorRange: ${{ vars.MIN_COVERAGE }}
        maxColorRange: 100

    - name: Update version badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_KEY }}
        gistID: 07bb4b086f8e7dea73754e73bc5c1bb2
        filename: symfo-base-version.json
        label: version
        message: ${{ inputs.version }}
        color: blue